name: .NET CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"

      - name: Restore
        run: |
          if ls *.slnx 1> /dev/null 2>&1; then
            dotnet restore
          else
            echo "Файл .slnx не найден. Пропуск Restore."
          fi

      - name: Build
        run: |
          if ls *.slnx 1> /dev/null 2>&1; then
            dotnet build --configuration Release --no-restore
          else
            echo "Файл .slnx не найден. Пропуск Build."
          fi

      - name: Test
        run: |
          if ls *.slnx 1> /dev/null 2>&1; then
            dotnet test --configuration Release --no-build --verbosity normal
          else
            echo "Файл .slnx не найден. Пропуск Test."
          fi
